FROM guacamole/guacamole:1.3.0

MAINTAINER michimau <mauro.michielon@eea.europa.eu>

#waiting for https://github.com/apache/guacamole-client/pull/566 to be merged
ADD etc/guacamole/start.sh /etc/guacamole/bin/start.sh
